// 图标统一来自 Semi Design（@douyinfe/semi-icons），本组件做语义名 → Semi 图标的映射，
// 保持旧版 iconfont 组件的 API（name/size/className/style）不变，调用点无需改动。
// 尺寸：Semi 的 svg 为 1em×1em，用 fontSize 精确控制像素；颜色通过 currentColor 继承。
import React from "react";
import {
  IconAIStrokedLevel2,
  IconArticle,
  IconAscend,
  IconBook,
  IconBolt,
  IconBriefcase,
  IconCalendar,
  IconCamera,
  IconChevronDown,
  IconChevronUp,
  IconClose,
  IconCode,
  IconColorPalette,
  IconCreditCard,
  IconDownload,
  IconEdit,
  IconEdit2,
  IconExternalOpen,
  IconGridRectangle,
  IconIdCard,
  IconImage,
  IconLink,
  IconMail,
  IconMapPin,
  IconMenu,
  IconPhone,
  IconPlus,
  IconPrize,
  IconPuzzle,
  IconRefresh2,
  IconShrink,
  IconStar,
  IconSync,
  IconTickCircle,
  IconVerify,
  IconCloudUploadStroked,
  IconApps,
} from "@douyinfe/semi-icons";

const ICONS = {
  "id": IconIdCard,
  "report": IconBriefcase,
  "book-2": IconBook,
  "puzzle": IconPuzzle,
  "bolt": IconBolt,
  "apps": IconApps,
  "brush": IconColorPalette,
  "layout": IconGridRectangle,
  "edit": IconEdit,
  "ai": IconAIStrokedLevel2,
  "download": IconDownload,
  "photo": IconImage,
  "code": IconCode,
  "file-text": IconArticle,
  "reload": IconRefresh2,
  "refresh": IconSync,
  "target": IconVerify,
  "layout-grid": IconShrink,
  "photo-plus": IconCamera,
  "plus": IconPlus,
  "close": IconClose,
  "more": IconMenu,
  "star": IconStar,
  "certificate": IconPrize,
  "calendar": IconCalendar,
  "mail": IconMail,
  "phone": IconPhone,
  "map-pin": IconMapPin,
  "link": IconLink,
  "cloud-upload": IconCloudUploadStroked,
  "external-link": IconExternalOpen,
  "sort-ascending": IconAscend,
  "check": IconTickCircle,
  "wallet": IconCreditCard,
  "chevron-up": IconChevronUp,
  "chevron-down": IconChevronDown,
} as const;

export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 16, className = "", style }: { name: IconName; size?: number; className?: string; style?: React.CSSProperties }) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp style={{ fontSize: size, ...style }} className={className} />;
}
